# Generated by Django 6.0.5 on 2026-06-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MqttUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('ativo', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Caminhão',
                'verbose_name_plural': 'Caminhões',
                'db_table': 'mqtt_users',
                'managed': True,
            },
        ),
    ]
